# Generated by Django 5.1.6 on 2025-03-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALAXIA', 'Galáxia'), ('ESTRELA', 'Estrela'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
