# Generated by Django 5.1.6 on 2025-03-17 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 23, 46, 37, 149586)),
        ),
    ]
