# Generated by Django 5.1.6 on 2025-03-18 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 13, 18, 47, 906881)),
        ),
    ]
