# Generated by Django 5.1.6 on 2025-03-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
        ('galeria', '0006_alter_fotografia_data_publicacao'),
    ]

    operations = [
    ]
